"""tours jadvali

Revision ID: 17bdbde09284
Revises: 70763ed5b20a
Create Date: 2026-07-28 23:32:29.472430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17bdbde09284'
down_revision: Union[str, Sequence[str], None] = '70763ed5b20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('region', postgresql.ENUM('Bostanliq', 'Zomin', 'Khiva', 'Samarkand', 'Bukhara', 'Tashkent', 'ToshkentViloyat', 'Namangan', 'Andijan', 'Fergana', 'Surkhandarya', 'Kashkadarya', 'Navoi', 'Syrdarya', 'Jizzakh', 'Khorezm', 'Karakalpakstan', name='listing_region', create_type=False), nullable=False),
    sa.Column('departure_city', sa.String(length=100), nullable=True),
    sa.Column('meeting_point', sa.String(length=500), nullable=False),
    sa.Column('difficulty', sa.Enum('Oson', 'Ortacha', 'Qiyin', 'Ekstremal', name='tour_difficulty'), nullable=False),
    sa.Column('group_size', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('extra_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('extra_fee_note', sa.String(length=500), nullable=True),
    sa.Column('price_basis', sa.String(length=200), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('meal_plan', sa.String(length=100), nullable=True),
    sa.Column('seats_left', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('cancellation_policy', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['tour_operators.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_operator_id'), 'tours', ['operator_id'], unique=False)
    op.create_index(op.f('ix_tours_owner_id'), 'tours', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tours_region'), 'tours', ['region'], unique=False)
    op.create_table('tour_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tour_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('total_estimate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='tour_booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_bookings_client_id'), 'tour_bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_tour_bookings_tour_id'), 'tour_bookings', ['tour_id'], unique=False)
    op.create_table('tour_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tour_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_photos_tour_id'), 'tour_photos', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_photos_tour_id'), table_name='tour_photos')
    op.drop_table('tour_photos')
    op.drop_index(op.f('ix_tour_bookings_tour_id'), table_name='tour_bookings')
    op.drop_index(op.f('ix_tour_bookings_client_id'), table_name='tour_bookings')
    op.drop_table('tour_bookings')
    op.drop_index(op.f('ix_tours_region'), table_name='tours')
    op.drop_index(op.f('ix_tours_owner_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_operator_id'), table_name='tours')
    op.drop_table('tours')
    # ### end Alembic commands ###
