"""rent_companies jadvali va listings.company_id

Revision ID: 1942fcefb19f
Revises: 17bdbde09284
Create Date: 2026-07-29 09:51:13.224040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1942fcefb19f'
down_revision: Union[str, Sequence[str], None] = '17bdbde09284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tin', sa.String(length=9), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=False),
    sa.Column('license_doc_name', sa.String(length=255), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=500), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('region', postgresql.ENUM('Bostanliq', 'Zomin', 'Khiva', 'Samarkand', 'Bukhara', 'Tashkent', 'ToshkentViloyat', 'Namangan', 'Andijan', 'Fergana', 'Surkhandarya', 'Kashkadarya', 'Navoi', 'Syrdarya', 'Jizzakh', 'Khorezm', 'Karakalpakstan', name='listing_region', create_type=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('work_hours', sa.String(length=100), nullable=True),
    sa.Column('pickup_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_mfo', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_companies_owner_id'), 'rent_companies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_rent_companies_region'), 'rent_companies', ['region'], unique=False)
    op.create_table('rent_company_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['rent_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_company_photos_company_id'), 'rent_company_photos', ['company_id'], unique=False)
    op.add_column('listings', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_listings_company_id'), 'listings', ['company_id'], unique=False)
    op.create_foreign_key(None, 'listings', 'rent_companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_index(op.f('ix_listings_company_id'), table_name='listings')
    op.drop_column('listings', 'company_id')
    op.drop_index(op.f('ix_rent_company_photos_company_id'), table_name='rent_company_photos')
    op.drop_table('rent_company_photos')
    op.drop_index(op.f('ix_rent_companies_region'), table_name='rent_companies')
    op.drop_index(op.f('ix_rent_companies_owner_id'), table_name='rent_companies')
    op.drop_table('rent_companies')
    # ### end Alembic commands ###
