"""audit log admin_id nullable, yangi audit action turlari

Revision ID: 226873f54073
Revises: 840fb5257f2f
Create Date: 2026-08-28 15:08:21.344856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226873f54073'
down_revision: Union[str, Sequence[str], None] = '840fb5257f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate yangi enum qiymatlarini aniqlamadi (Postgres enum'larga
    # oldin ham xos muammo — CLAUDE.md'dagi boshqa modullardagi izohlarga
    # qarang) — qo'lda qo'shiladi.
    op.execute("ALTER TYPE admin_audit_action ADD VALUE IF NOT EXISTS 'admin_role_change'")
    op.execute("ALTER TYPE admin_audit_action ADD VALUE IF NOT EXISTS 'admin_delete'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_log', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('admin_audit_log_admin_id_fkey'), 'admin_audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'admin_audit_log', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('admin_audit_log_admin_id_fkey'), 'admin_audit_log', 'users', ['admin_id'], ['id'])
    op.alter_column('admin_audit_log', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
