"""guides jadvali va tours guide_id

Revision ID: 3da676277374
Revises: 1942fcefb19f
Create Date: 2026-07-29 10:26:05.097809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3da676277374'
down_revision: Union[str, Sequence[str], None] = '1942fcefb19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('guide_type', sa.Enum('Individual', 'Ekskursovod', 'TogGidi', 'GidHaydovchi', name='guide_type'), nullable=False),
    sa.Column('employment', sa.Enum('Mustaqil', 'Turagentlik', 'Muzey', name='guide_employment'), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('license_doc_name', sa.String(length=255), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('tin', sa.String(length=9), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('region', postgresql.ENUM('Bostanliq', 'Zomin', 'Khiva', 'Samarkand', 'Bukhara', 'Tashkent', 'ToshkentViloyat', 'Namangan', 'Andijan', 'Fergana', 'Surkhandarya', 'Kashkadarya', 'Navoi', 'Syrdarya', 'Jizzakh', 'Khorezm', 'Karakalpakstan', name='listing_region', create_type=False), nullable=False),
    sa.Column('office', sa.String(length=500), nullable=True),
    sa.Column('service_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hourly_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('daily_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_includes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_group_size', sa.String(length=100), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=500), nullable=True),
    sa.Column('has_car', sa.Boolean(), nullable=False),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('car_seats', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guides_owner_id'), 'guides', ['owner_id'], unique=False)
    op.create_index(op.f('ix_guides_region'), 'guides', ['region'], unique=False)
    op.create_table('guide_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guide_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_photos_guide_id'), 'guide_photos', ['guide_id'], unique=False)
    op.add_column('tours', sa.Column('guide_id', sa.Uuid(), nullable=True))
    op.alter_column('tours', 'operator_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_tours_guide_id'), 'tours', ['guide_id'], unique=False)
    op.create_foreign_key(None, 'tours', 'guides', ['guide_id'], ['id'])
    op.create_check_constraint(
        'ck_tours_exactly_one_owner_profile',
        'tours',
        '(operator_id IS NOT NULL AND guide_id IS NULL) OR '
        '(operator_id IS NULL AND guide_id IS NOT NULL)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tours_exactly_one_owner_profile', 'tours', type_='check')
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_index(op.f('ix_tours_guide_id'), table_name='tours')
    op.alter_column('tours', 'operator_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tours', 'guide_id')
    op.drop_index(op.f('ix_guide_photos_guide_id'), table_name='guide_photos')
    op.drop_table('guide_photos')
    op.drop_index(op.f('ix_guides_region'), table_name='guides')
    op.drop_index(op.f('ix_guides_owner_id'), table_name='guides')
    op.drop_table('guides')
    # ### end Alembic commands ###
