"""listing video_url va license_doc_url ustunlari

Revision ID: 66ee07f668c0
Revises: b52a53b372db
Create Date: 2026-08-04 09:18:22.840537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ee07f668c0'
down_revision: Union[str, Sequence[str], None] = 'b52a53b372db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('license_doc_url', sa.String(length=500), nullable=True))
    op.add_column('listings', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'video_url')
    op.drop_column('listings', 'license_doc_url')
    # ### end Alembic commands ###
