"""plan_purchases jadvali va wallet_tx_kind ga plan qoshish

Revision ID: 6bb61c910ef0
Revises: 0e5142725a1e
Create Date: 2026-07-30 08:48:22.940208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb61c910ef0'
down_revision: Union[str, Sequence[str], None] = '0e5142725a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE wallet_tx_kind ADD VALUE IF NOT EXISTS 'plan'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Enum('free', 'standard', 'business', 'premium', name='plan_id_enum'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='plan_billing_cycle'), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_purchases_user_id'), 'plan_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_purchases_user_id'), table_name='plan_purchases')
    op.drop_table('plan_purchases')
    # ### end Alembic commands ###
    # Eslatma: Postgres ALTER TYPE ... DROP VALUE'ni to'g'ridan-to'g'ri qo'llab-quvvatlamaydi,
    # shuning uchun 'plan' qiymati wallet_tx_kind'da qoladi (downgrade uni olib tashlamaydi).
