"""tour_operators jadvali

Revision ID: 70763ed5b20a
Revises: c39ef6801c04
Create Date: 2026-07-28 23:16:57.507584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70763ed5b20a'
down_revision: Union[str, Sequence[str], None] = 'c39ef6801c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_operators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tin', sa.String(length=9), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=False),
    sa.Column('license_doc_name', sa.String(length=255), nullable=True),
    sa.Column('license_issued', sa.String(length=255), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=False),
    sa.Column('spec_tag', sa.Enum('Tarixiy', 'Ekoturizm', 'Xalqaro', 'HajUmra', name='operator_spec_tag'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=500), nullable=False),
    sa.Column('region', postgresql.ENUM('Bostanliq', 'Zomin', 'Khiva', 'Samarkand', 'Bukhara', 'Tashkent', 'ToshkentViloyat', 'Namangan', 'Andijan', 'Fergana', 'Surkhandarya', 'Kashkadarya', 'Navoi', 'Syrdarya', 'Jizzakh', 'Khorezm', 'Karakalpakstan', name='listing_region', create_type=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_operators_owner_id'), 'tour_operators', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tour_operators_region'), 'tour_operators', ['region'], unique=False)
    op.create_table('tour_operator_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['tour_operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_operator_photos_operator_id'), 'tour_operator_photos', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_operator_photos_operator_id'), table_name='tour_operator_photos')
    op.drop_table('tour_operator_photos')
    op.drop_index(op.f('ix_tour_operators_region'), table_name='tour_operators')
    op.drop_index(op.f('ix_tour_operators_owner_id'), table_name='tour_operators')
    op.drop_table('tour_operators')
    # ### end Alembic commands ###
