"""admin rol darajalari

Revision ID: 840fb5257f2f
Revises: d4acc803f481
Create Date: 2026-08-28 14:57:18.044249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840fb5257f2f'
down_revision: Union[str, Sequence[str], None] = 'd4acc803f481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate `add_column`ga PG enum turini avtomatik yaratmadi —
    # qo'lda oldindan yaratiladi (`create_type=False`, keyin ustun).
    admin_role_enum = sa.Enum(
        'super', 'moderator', 'finance', 'content', name='admin_role'
    )
    admin_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'admin_role',
            sa.Enum('super', 'moderator', 'finance', 'content', name='admin_role', create_type=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    # `role != 'ADMIN'` bo'lsa `admin_role` mazmunsiz — NULL bo'lishi shart
    # (Tours'dagi `ck_tours_exactly_one_owner_profile` bilan bir xil qo'lda
    # qo'shilgan CHECK constraint naqshi — autogenerate buni aniqlamaydi).
    op.create_check_constraint(
        'ck_users_admin_role_only_for_admin',
        'users',
        "(role = 'ADMIN') OR (admin_role IS NULL)",
    )

    # Ma'lumot migratsiyasi: mavjud ADMIN foydalanuvchilar orasidan eng
    # birinchi yaratilgani 'super' bilan boshlanadi (aks holda tizim
    # egasiz qolib ketardi), qolganlari xavfsiz sukut 'moderator' bilan.
    op.execute(
        """
        UPDATE users SET admin_role = 'super'
        WHERE id = (
            SELECT id FROM users WHERE role = 'ADMIN'
            ORDER BY created_at ASC LIMIT 1
        )
        """
    )
    op.execute(
        "UPDATE users SET admin_role = 'moderator' "
        "WHERE role = 'ADMIN' AND admin_role IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_admin_role_only_for_admin', 'users', type_='check')
    op.drop_column('users', 'admin_role')
    # ### end Alembic commands ###
