"""admin moduli - audit log, ban, reject maydonlari

Revision ID: afda567877d4
Revises: 6bb61c910ef0
Create Date: 2026-07-30 10:05:30.441511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afda567877d4'
down_revision: Union[str, Sequence[str], None] = '6bb61c910ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('listing_approve', 'listing_reject', 'listing_pause', 'tour_approve', 'tour_reject', 'review_delete', 'user_ban', 'user_unban', 'admin_invite', name='admin_audit_action'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.add_column(
        'listings',
        sa.Column('rejected', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('listings', sa.Column('reject_reason', sa.String(length=500), nullable=True))
    op.add_column(
        'tours',
        sa.Column('rejected', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('tours', sa.Column('reject_reason', sa.String(length=500), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('users', sa.Column('banned_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned_reason')
    op.drop_column('users', 'is_banned')
    op.drop_column('tours', 'reject_reason')
    op.drop_column('tours', 'rejected')
    op.drop_column('listings', 'reject_reason')
    op.drop_column('listings', 'rejected')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
