"""bookings jadvali

Revision ID: c39ef6801c04
Revises: 48f512ad6401
Create Date: 2026-07-28 22:26:31.298939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39ef6801c04'
down_revision: Union[str, Sequence[str], None] = '48f512ad6401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'rejected', 'cancelled', name='booking_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prepay_percent', sa.Integer(), nullable=False),
    sa.Column('escrow', sa.Enum('held', 'released', 'refunded', name='booking_escrow_status'), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=500), nullable=True),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.Column('guest_phone', sa.String(length=20), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cancelled_by', sa.Enum('guest', 'host', name='booking_cancelled_by'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_listing_id'), 'bookings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_bookings_owner_id'), 'bookings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_owner_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_listing_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
