"""tour_bookings departure ustuni

Revision ID: d4acc803f481
Revises: 66ee07f668c0
Create Date: 2026-08-07 19:03:10.154400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4acc803f481'
down_revision: Union[str, Sequence[str], None] = '66ee07f668c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_bookings', sa.Column('departure', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_bookings', 'departure')
    # ### end Alembic commands ###
