"""listings jadvali

Revision ID: fb7787f22310
Revises: 71bb7fe2ec47
Create Date: 2026-07-24 10:10:45.874682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7787f22310'
down_revision: Union[str, Sequence[str], None] = '71bb7fe2ec47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('Dacha', 'Hotel', 'Boutique', 'Hostel', 'Recreation', 'Camping', 'Villa', 'Sanatorium', 'RentCar', 'Dining', name='listing_type'), nullable=False),
    sa.Column('region', sa.Enum('Bostanliq', 'Zomin', 'Khiva', 'Samarkand', 'Bukhara', 'Tashkent', 'ToshkentViloyat', 'Namangan', 'Andijan', 'Fergana', 'Surkhandarya', 'Kashkadarya', 'Navoi', 'Syrdarya', 'Jizzakh', 'Khorezm', 'Karakalpakstan', name='listing_region'), nullable=False),
    sa.Column('weekday_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weekend_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_listings_region'), 'listings', ['region'], unique=False)
    op.create_index(op.f('ix_listings_type'), 'listings', ['type'], unique=False)
    op.create_table('listing_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_photos_listing_id'), 'listing_photos', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_photos_listing_id'), table_name='listing_photos')
    op.drop_table('listing_photos')
    op.drop_index(op.f('ix_listings_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_region'), table_name='listings')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
